stages:
  pull
  dependencies
  build
  # depoly

fetch_repo:
  stage: pull
  script:
    - mkdir /var/www/power-tools/
    - cd /var/www/power-tools/
    - ../gitClone.sh "git@172.16.17.29:front-end/power-tools.git" "power-tools" "dev"
  only:
    - dev
  except:
    - triggers

install_deps:
  stage: dependencies
  only:
    - dev
  script:
    cd /var/www/power-tools/power-tools
    - yarn install
  except:
    - triggers

build:
  stage: build
  only:
    - dev
  script:
    cd /var/www/power-tools/power-tools
    - yarn run build:h5
  except:
    - triggers
